/**
 * The route table the ledger checks against: every route deejaytools-api
 * registers, as Hono writes them (70). In deejaytools-api the ledger read
 * this from the in-process app (`app.routes`); this copy only drives a
 * target over HTTP, so the table is fixed here. It is the contract the
 * replacement must cover, and changes only if that contract does.
 */
export const ROUTES: readonly string[] = [
  "GET /health",
  "GET /internal/tick",
  "POST /v1/admin/checkins",
  "DELETE /v1/admin/checkins/test",
  "GET /v1/admin/checkins/test",
  "GET /v1/admin/drive-jobs",
  "POST /v1/admin/drive-jobs/:id/retry",
  "POST /v1/admin/drive-jobs/backfill-renames",
  "GET /v1/admin/drive-jobs/summary",
  "GET /v1/admin/event-song-submissions",
  "GET /v1/admin/songs",
  "GET /v1/admin/users",
  "GET /v1/admin/users/:id/event-song-submissions",
  "GET /v1/admin/users/:id/partners",
  "PATCH /v1/admin/users/:id/role",
  "GET /v1/auth/me",
  "PATCH /v1/auth/me",
  "POST /v1/auth/sync",
  "POST /v1/checkins",
  "DELETE /v1/checkins/:id",
  "GET /v1/checkins/mine",
  "GET /v1/event-song-submissions",
  "POST /v1/event-song-submissions",
  "DELETE /v1/event-song-submissions/:id",
  "GET /v1/events",
  "POST /v1/events",
  "DELETE /v1/events/:id",
  "GET /v1/events/:id",
  "PATCH /v1/events/:id",
  "GET /v1/events/:id/entities",
  "POST /v1/feedback",
  "GET /v1/managed-partnerships",
  "POST /v1/managed-partnerships",
  "DELETE /v1/managed-partnerships/:id",
  "PATCH /v1/managed-partnerships/:id",
  "POST /v1/pairs/find-or-create",
  "GET /v1/partners",
  "POST /v1/partners",
  "DELETE /v1/partners/:id",
  "GET /v1/partners/:id",
  "PATCH /v1/partners/:id",
  "GET /v1/partners/:id/associations",
  "GET /v1/partners/leading-pairs",
  "GET /v1/queue/:sessionId/active",
  "GET /v1/queue/:sessionId/non-priority",
  "GET /v1/queue/:sessionId/priority",
  "GET /v1/queue/:sessionId/waiting",
  "POST /v1/queue/complete",
  "POST /v1/queue/incomplete",
  "POST /v1/queue/move-down",
  "POST /v1/queue/promote",
  "POST /v1/queue/withdraw",
  "GET /v1/runs",
  "GET /v1/sessions",
  "POST /v1/sessions",
  "DELETE /v1/sessions/:id",
  "GET /v1/sessions/:id",
  "PATCH /v1/sessions/:id",
  "PUT /v1/sessions/:id/divisions",
  "PATCH /v1/sessions/:id/status",
  "GET /v1/songs",
  "POST /v1/songs",
  "DELETE /v1/songs/:id",
  "GET /v1/songs/:id",
  "PATCH /v1/songs/:id",
  "POST /v1/songs/upload/chunk",
  "GET /v1/teams",
  "POST /v1/teams",
  "DELETE /v1/teams/:id",
  "PATCH /v1/teams/:id",
];
